apiVersion: v1alpha
kind: testcafe
metadata:
  name: Testing TestCafe Support
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
suites:
  - name: "saucy test"
    browser: "firefox"
    src:
      - ".*.(spec|test).[jt]s$"
    screenshots:
      takeOnFails: true
    platformName: "windows 10"
    env:
      hello: world

docker:
  fileTransfer: copy
  #image:

testcafe:
  projectPath: tests/e2e/testcafe
  version: 1.8.5

sauce:
  region: us-west-1
